version: '3'

services:
  flask-app:
    build:
      context: ./backend
    image: movie_db_backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env  # Specify the .env file to load the environment variables
    environment:
      - FLASK_RUN_HOST=0.0.0.0

volumes: {}
