# name: Format Code

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# jobs:
#   format:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Check out the repository code
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Step 2: Set up Python
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.8

#       # Step 3: Install Black
#       - name: Install Black
#         run: |
#           python -m venv venv
#           source venv/bin/activate
#           pip install black

#       # Step 4: Run Black to Check Formatting
#       - name: Check Code Formatting
#         run: |
#           source venv/bin/activate
#           black --check backend/

#       # Step 5: Optional - Auto-format Code
#       - name: Auto-format Code (Optional)
#         if: github.event_name == 'pull_request'
#         run: |
#           source venv/bin/activate
#           black backend/


name: Format Code

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Black
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install black

      - name: Auto-format Code
        run: |
          source venv/bin/activate
          black backend/

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add backend/
          git commit -m "Auto-format code with Black" || echo "No changes to commit"
          git push origin main
